### PR TITLE
Allow all NServiceBus core versions

### PR DESCRIPTION
**Pull request by andreasohlund**
No need to require v7.2.2

### CODE REVIEW

**Comment by bording** [comment]
I don't really agree with this change. Why allow the package to work with unsupported versions of core?

7.0.x hasn't been supported for almost a year now. It think we should be pushing the minimum version forward to at least a currently supported version, especially considering how transitive package references work.

Maybe, going back to 7.1.11, as the oldest minimum supported version, but not 7.0.0! Though 7.1.x is going out of support soon as well.

**Comment by SeanFeldman** [comment]
I agree with @bording. 7.1 is out of support in April 2020.

**Comment by timbussmann** [comment]
I can understand @bording point but is there really a downside of targeting 7.0 as long as we don't need any of the newer features?
The main reason I could see is that people would by default pull in an older version of core when they start by referencing this package instead of core?

**Comment by andreasohlund** [comment]
Fair point, I was thinking more from a technical standpoint "what was added in v7.2 that this package reguires" => nothing.

I'd didn't consider the angle of nudging the users to upgrade. If we go with this should we make this a common policy when releasing downstreams or is this a one of since its a new package? 

Eg. if we ship a new minor of NH (there is one likely coming up) , would we change https://github.com/Particular/NServiceBus.NHibernate/blob/master/src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj#L17 to require v7.2.2 of core?

**Comment by timbussmann** [comment]
> I'd didn't consider the angle of nudging the users to upgrade. If we go with this should we make this a common policy when releasing downstreams or is this a one of since its a new package?

I was wondering about this too. Is it worth creating some guidance around that to keep behavior consistent?

**Comment by bording** [comment]
> I'd didn't consider the angle of nudging the users to upgrade. If we go with this should we make this a common policy when releasing downstreams or is this a one of since its a new package?

Yes I think we should be making this a common policy. Also, think about what will happen once Dependabot learns about version ranges: it will be trying to keep those updated as well.

**Comment by andreasohlund** [comment]
Decided to keep 7.2.2 since this is a new package.

**Pull request closed without merging**
